# default config.yml

# The host name and port to listen on
# hostname - ip address or hostname to allow connections from, default is "0.0.0.0" 
#            (any). "localhost" would prevent remote clients from connecting.
hostname: 
port: 4711

# Determine whether locations are RELATIVE to the spawn point (default like pi) or ABSOLUTE
location: ABSOLUTE

# Determine whether hit events are triggered by LEFT clicks, RIGHT clicks or BOTH
hitclick: RIGHT

# Determine the maxinum number of commands that can be executed in a single tick
maxcommandspertick: 1000

# Determine the maxinum number of commands that can be executed in a single tick by a single player
maxcommandsperplayer: 100

# Determine the maxinum number of commands that can be executed over a sustained period
maxsustainedcommands: 5000

# Determine the number of ticks per sustained period
sustainedticks: 100

# Determine the maximum radius from spawn or the executing player, blocks may be set or be teleported too
maxdistance: 1535

# List of all blocks ids to enact a block specific sustained time period block limit
blocklimitlist: [46]

# List of all sustained block limits in the order in which the block ids appear in blocklimitlist
blocklimits: [50]

# Maximum size for a single block command
maxblocks: 100000

# Maximum postToChat in a sustained period
maxsustainedchat: 20

# Whether or not you can execute API commands when no player is present
allowhostlesscommands: true
